version: '3'

services:
  nginx:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    working_dir: /srv/web
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/srv/web
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    working_dir: /srv/web
    volumes:
      - ./src:/srv/web
      - ${HOME}/.composer:${HOME}/.composer
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      # - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    working_dir: /srv/web
    volumes:
      - ./src:/srv/web
      - ${HOME}/.npm:${HOME}/.npm
    command: npm run hot
    ports:
      - 8080:8080